apiVersion: v1
kind: Service
metadata:
  name: rules-engine
  labels:
    app: rules-engine
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: rules-engine
