apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: webscraper
build:
  artifacts:
    - image: webscraper
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
profiles:
  - name: dev
    build:
      tagPolicy:
        sha256: {}
    deploy:
      kubectl: {}
