apiVersion: v1
kind: Service
metadata:
  name: frontend-react
  labels:
    app: frontend-react
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend-react
