apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-flutterflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-flutterflow
  template:
    metadata:
      labels:
        app: frontend-flutterflow
    spec:
      serviceAccountName: gke-sa
      automountServiceAccountToken: true
      containers:
        - name: frontend-flutterflow
          image: frontend-flutterflow
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            requests:
              cpu: "250m"
              memory: "100Mi"
            limits:
              memory: "5000Mi"
              cpu: "2000m"
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
