// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export type ILang = {
  code: string
  name: string
  flag: string
}

export const supportedLangs: ILang[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇲🇽" },
  { code: "af", name: "Afrikaans", flag: "🇿🇦" },
  { code: "sq", name: "Shqip", flag: "🇦🇱" },
  { code: "am", name: "አማርኛ", flag: "🇪🇹" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "hy", name: "Հայերեն", flag: "🇦🇲" },
  { code: "az", name: "Azərbaycan", flag: "🇦🇿" },
  { code: "eu", name: "Euskara", flag: "🇪🇸" },
  { code: "be", name: "Беларуская", flag: "🇧🇾" },
  { code: "bm", name: "Bamanankan", flag: "🇲🇱" },
  { code: "bs", name: "Bosanski", flag: "🇧🇦" },
  { code: "bho", name: "भोजपुरी", flag: "🇮🇳" },
  { code: "bg", name: "Български", flag: "🇧🇬" },
  { code: "ca", name: "Català", flag: "🇪🇸" },
  { code: "ceb", name: "Cebuano", flag: "🇵🇭" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "co", name: "Corsu", flag: "🇫🇷" },
  { code: "hr", name: "Hrvatski", flag: "🇭🇷" },
  { code: "cs", name: "Čeština", flag: "🇨🇿" },
  { code: "da", name: "Dansk", flag: "🇩🇰" },
  { code: "dv", name: "ދިވެހި", flag: "🇲🇻" },
  { code: "doi", name: "डोगरी", flag: "🇮🇳" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "eo", name: "Esperanto", flag: "🇪🇸" },
  { code: "et", name: "Eesti", flag: "🇪🇪" },
  { code: "ee", name: "Eʋegbe", flag: "🇬🇭" },
  { code: "fil", name: "Filipino", flag: "🇵🇭" },
  { code: "fi", name: "Suomi", flag: "🇫🇮" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "fy", name: "Frysk", flag: "🇳🇱" },
  { code: "gl", name: "Galego", flag: "🇪🇸" },
  { code: "ka", name: "ქართული", flag: "🇬🇪" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "el", name: "Ελληνικά", flag: "🇬🇷" },
  { code: "gn", name: "Avañe'ẽ", flag: "🇵🇾" },
  { code: "gu", name: "ગુજરાતી", flag: "🇮🇳" },
  { code: "ht", name: "Kreyòl Ayisyen", flag: "🇭🇹" },
  { code: "ha", name: "هَوُسَ", flag: "🇳🇬" },
  { code: "haw", name: "ʻŌlelo Hawaiʻi", flag: "🇺🇸" },
  { code: "he", name: "עברית", flag: "🇮🇱" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "hmn", name: "Hmoob", flag: "🇲🇲" },
  { code: "hu", name: "Magyar", flag: "🇭🇺" },
  { code: "is", name: "Íslenska", flag: "🇮🇸" },
  { code: "ig", name: "Igbo", flag: "🇳🇬" },
  { code: "ilo", name: "Ilokano", flag: "🇵🇭" },
  { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ga", name: "Gaeilge", flag: "🇮🇪" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "jv", name: "Basa Jawa", flag: "🇮🇩" },
  { code: "kn", name: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "kk", name: "Қазақша", flag: "🇰🇿" },
  { code: "km", name: "ភាសាខ្មែរ", flag: "🇰🇭" },
  { code: "rw", name: "Ikinyarwanda", flag: "🇷🇼" },
  { code: "gom", name: "कोंकणी", flag: "🇮🇳" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "kri", name: "Krio", flag: "🇸🇱" },
  { code: "ku", name: "Kurdî", flag: "🇮🇷" },
  { code: "ckb", name: "کوردی", flag: "🇮🇷" },
  { code: "ky", name: "Кыргызча", flag: "🇰🇬" },
  { code: "lo", name: "ພາສາລາວ", flag: "🇱🇦" },
  { code: "la", name: "Latina", flag: "🇻🇦" },
  { code: "lv", name: "Latviešu", flag: "🇱🇻" },
  { code: "ln", name: "Lingála", flag: "🇨🇩" },
  { code: "lt", name: "Lietuvių", flag: "🇱🇹" },
  { code: "lb", name: "Lëtzebuergesch", flag: "🇱🇺" },
  { code: "mk", name: "Македонски", flag: "🇲🇰" },
  { code: "mai", name: "मैथिली", flag: "🇮🇳" },
  { code: "mg", name: "Malagasy", flag: "🇲🇬" },
  { code: "ms", name: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "ml", name: "മലയാളം", flag: "🇮🇳" },
  { code: "mt", name: "Malti", flag: "🇲🇹" },
  { code: "mi", name: "Māori", flag: "🇳🇿" },
  { code: "mr", name: "मराठी", flag: "🇮🇳" },
  // { code: "mni-Mtei", name: "মৈইতৈইলোন্", flag: "🇮🇳" },
  { code: "lus", name: "Mizo", flag: "🇮🇳" },
  { code: "mn", name: "Монгол", flag: "🇲🇳" },
  { code: "my", name: "ဗမာစာ", flag: "🇲🇲" },
  { code: "ne", name: "नेपाली", flag: "🇳🇵" },
  { code: "no", name: "Norsk", flag: "🇳🇴" },
  { code: "ny", name: "Chi-Chewa", flag: "🇲🇼" },
  { code: "or", name: "ଓଡ଼ିଆ", flag: "🇮🇳" },
  { code: "om", name: "Oromoo", flag: "🇪🇹" },
  { code: "ps", name: "پښتو", flag: "🇵🇸" },
  { code: "fa", name: "فارسی", flag: "🇮🇷" },
  { code: "pl", name: "Polski", flag: "🇵🇱" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "pa", name: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "qu", name: "Runa Simi", flag: "🇵🇪" },
  { code: "ro", name: "Română", flag: "🇷🇴" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "sm", name: "Gagana Samoa", flag: "🇼🇸" },
  { code: "sa", name: "संस्कृतम्", flag: "🇮🇳" },
  { code: "gd", name: "Gàidhlig", flag: "🇬🇧" },
  { code: "nso", name: "Sesotho sa Leboa", flag: "🇿🇦" },
  { code: "sr", name: "Српски", flag: "🇷🇸" },
  { code: "st", name: "Sesotho", flag: "🇿🇦" },
  { code: "sn", name: "chiShona", flag: "🇿🇼" },
  { code: "sd", name: "सिन्धी", flag: "🇮🇳" },
  { code: "si", name: "සිංහල", flag: "🇱🇰" },
  { code: "sk", name: "Slovenčina", flag: "🇸🇰" },
  { code: "sl", name: "Slovenščina", flag: "🇸🇮" },
  { code: "so", name: "Soomaaliga", flag: "🇸🇴" },
  { code: "su", name: "Basa Sunda", flag: "🇮🇩" },
  { code: "sw", name: "Kiswahili", flag: "🇰🇪" },
  { code: "sv", name: "Svenska", flag: "🇸🇪" },
  { code: "tl", name: "Tagalog", flag: "🇵🇭" },
  { code: "tg", name: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "ta", name: "தமிழ்", flag: "🇮🇳" },
  { code: "tt", name: "Татарча", flag: "🇷🇺" },
  { code: "te", name: "తెలుగు", flag: "🇮🇳" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "ti", name: "ትግርኛ", flag: "🇪🇹" },
  { code: "ts", name: "Xitsonga", flag: "🇿🇦" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "tk", name: "Türkmençe", flag: "🇹🇲" },
  { code: "ak", name: "Akan", flag: "🇬🇭" },
  { code: "uk", name: "Українська", flag: "🇺🇦" },
  { code: "ur", name: "اردو", flag: "🇵🇰" },
  { code: "ug", name: "ئۇيغۇرچە", flag: "🇨🇳" },
  { code: "uz", name: "Oʻzbek", flag: "🇺🇿" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "cy", name: "Cymraeg", flag: "🇬🇧" },
  { code: "xh", name: "isiXhosa", flag: "🇿🇦" },
  { code: "yi", name: "ייִדיש", flag: "🇮🇱" },
  { code: "yo", name: "Yorùbá", flag: "🇳🇬" },
  { code: "zu", name: "isiZulu", flag: "🇿🇦" },
]
