from config.config import (
    # platform config
    PROJECT_ID,
    GCP_PROJECT,
    REGION,
    SKAFFOLD_NAMESPACE,
    GKE_CLUSTER,
    GCP_ZONE,
    DATABASE_PREFIX,
    USER_MANAGEMENT_BASE_URL,
    RULES_ENGINE_BASE_URL,
    SERVICES,

    # service config
    LLM_SERVICE_PATH,
    PORT,
    API_BASE_URL,
    CONTAINER_NAME,
    DEPLOYMENT_NAME,
    SERVICE_NAME,
    PAYLOAD_FILE_SIZE,
    ERROR_RESPONSES,
    JOB_NAMESPACE,
    auth_client,

    # secrets
    LLM_BACKEND_ROBOT_USERNAME,
    LLM_BACKEND_ROBOT_PASSWORD,

    # LLM types
    LLM_TYPES,
    CHAT_LLM_TYPES,
    OPENAI_LLM_TYPE_GPT3_5,
    OPENAI_LLM_TYPE_GPT4,
    COHERE_LLM_TYPE,
    VERTEX_LLM_TYPE_BISON_TEXT,
    VERTEX_LLM_TYPE_BISON_CHAT,
    VERTEX_AI_MODEL_GARDEN_LLAMA2_CHAT,
    TRUSS_LLM_LLAMA2_CHAT,

    # LLM config
    ENABLE_OPENAI_LLM,
    ENABLE_COHERE_LLM,

    # LLM models and collections of models
    DEFAULT_QUERY_CHAT_MODEL,
    DEFAULT_QUERY_EMBEDDING_MODEL,
    GOOGLE_LLM,
    LANGCHAIN_LLM,
    EMBEDDING_MODELS,
    LANGCHAIN_EMBEDDING_MODELS,
    VERTEX_EMBEDDING_MODELS,
    LLM_SERVICE_EMBEDDING_MODELS,
    GOOGLE_MODEL_GARDEN,
    LLM_SERVICE_MODELS,
    LLM_TRUSS_MODELS,

    # Endpoints
    MODEL_GARDEN_LLAMA2_CHAT_ENDPOINT_ID,

    # agent config
    AGENT_CONFIG_PATH,
    )

from config.vector_store_config import (
  DEFAULT_VECTOR_STORE,
  VECTOR_STORES
  )

