apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-frontend_streamlit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend_streamlit
  minReplicas: 3
  maxReplicas: 110
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
