# skaffold.yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ingress

profiles:
  - &gke-profile # YAML anchor used by "default" profile.
    name: gke
    manifests:
      kustomize:
        paths:
          - ./kustomize/gke
    deploy:
      kubectl: {}

  - &genie-profile # YAML anchor used by "genie" profile.
    name: genie
    manifests:
      kustomize:
        paths:
          - ./kustomize/genie
    deploy:
      kubectl: {}

  - &genie-llama2-profile # YAML anchor used by "genie-llama2" profile.
    name: genie-llama2
    manifests:
      kustomize:
        paths:
          - ./kustomize/genie-llama2
    deploy:
      kubectl: {}

  # The default-deploy profile refers to gke profile above.
  - <<: *gke-profile
    name: default-deploy

  # The genie-deploy profile refers to genie profile above.
  - <<: *genie-profile
    name: genie-deploy

  # The genie-llama2-deploy profile refers to genie-llama2 profile above.
  - <<: *genie-profile
    name: genie-llama2-deploy
