# skaffold.yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ingress

profiles:
  - &gke-profile # YAML anchor used by "default" profile.
    name: gke
    manifests:
      kustomize:
        paths:
          - ./kustomize/gke
    deploy:
      kubectl: {}

  - &genie-profile # YAML anchor used by "genie" profile.
    name: genie
    manifests:
      kustomize:
        paths:
          - ./kustomize/genie
    deploy:
      kubectl: {}

  # The default-deploy profile refer to gke profile above.
  - <<: *gke-profile
    name: default-deploy

  # The default-deploy profile refer to gke profile above.
  - <<: *genie-profile
    name: genie-deploy
