apiVersion: v1
kind: Service
metadata:
  name: tools-service
  labels:
    app: tools-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: tools-service
