name: GKE - Deploy microservices to dev
on:
  push:
    branches:
      - main
    paths:
      - "components/**"
      - "utils/**"
      - ".github/workflows/deployment_gke_dev.yaml"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  SKAFFOLD_DEFAULT_REPO: gcr.io/gcp-mira-demo
  SKAFFOLD_NAMESPACE: ${{ vars.GKE_NAMESPACE }}
  GKE_CLUSTER: main-cluster
  GKE_REGION: us-central1
  KUSTOMIZE_VERSION: 5.0.0
  SKAFFOLD_VERSION: 2.4.0
  SKAFFOLD_CACHE_GCS: gs://artifacts.gcp-mira-demo.appspot.com/skaffold/cache

# copier:raw
jobs:
  deploy_backends:
    name: Deploy microservices to GKE cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: auth
        name: Auth with Service Account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          # FIXME: Use workload identity instead of service account key.
          # workload_identity_provider: ''

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin, alpha

      - name: Connect to cluster
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --region $GKE_REGION --project $PROJECT_ID

      - name: Set up Service Account
        run: |
          NAMESPACE=${SKAFFOLD_NAMESPACE} bash setup/setup_ksa.sh

      - name: Install Kustomize
        run: |
          wget -O kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v$KUSTOMIZE_VERSION/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
          sudo tar -xvf kustomize.tar.gz -C /usr/local/bin/

      - name: Install Solutions Builder
        run: |
          pip install -U solutions-builder

      - name: Update the project id in config files
        run: |
          sb set project-id $PROJECT_ID --yes

      - name: Retrieve Firebase API key
        run: |
          KEY_NAME=$(gcloud alpha services api-keys list --filter="displayName='API Key for Identity Platform'" --format="value(name)")
          export FIREBASE_API_KEY=$(gcloud alpha services api-keys get-key-string ${KEY_NAME} --format="value(keyString)")
          echo "FIREBASE_API_KEY = $FIREBASE_API_KEY"

      - name: Install Skaffold release binary
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v$SKAFFOLD_VERSION/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/skaffold

      - name: Set default repo for Skaffold
        run: |
          skaffold config set default-repo "$SKAFFOLD_DEFAULT_REPO"

      - name: Download Skaffold cache if exists
        run: |
          gsutil cp $SKAFFOLD_CACHE_GCS ~/.skaffold/ || true

      - name: Build and deploy to cluster
        run: |
          sb deploy --yes

      - name: Upload Skaffold cache
        if: always()
        run: |
          gsutil cp ~/.skaffold/cache $SKAFFOLD_CACHE_GCS

# copier:endraw
